### ISSUE TITLE
currently not support laravel/framework v5.5.28

### ISSUE THREAD

**Issue by memordial** [feelinc/laravel-bank-statements#3]
$ composer require sule/bank-statements
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "C:/ProgramData/ComposerSetup/bin/composer.phar self-update" to get the latest version.
Using version ^1.0 for sule/bank-statements
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.5.28
    - Conclusion: don't install laravel/framework v5.5.28
    - sule/bank-statements v1.0.0 requires illuminate/support 5.1.* || 5.2.* || 5.3.* || 5.4.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - sule/bank-statements v1.0.1 requires illuminate/support 5.1.* || 5.2.* || 5.3.* || 5.4.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - sule/bank-statements v1.0.2 requires illuminate/support 5.1.* || 5.2.* || 5.3.* || 5.4.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - sule/bank-statements v1.0.3 requires illuminate/support 5.1.* || 5.2.* || 5.3.* || 5.4.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - don't install illuminate/support v5.1.1|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.1.13|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.1.16|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.1.2|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.1.20|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.1.22|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.1.25|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.1.28|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.1.30|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.1.31|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.1.41|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.1.6|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.1.8|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.2.0|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.2.19|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.2.21|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.2.24|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.2.25|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.2.26|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.2.27|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.2.28|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.2.31|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.2.32|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.2.37|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.2.43|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.2.45|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.2.6|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.2.7|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.3.0|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.3.16|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.3.23|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.3.4|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.4.0|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.4.13|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.4.17|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.4.19|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.4.27|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.4.36|don't install laravel/framework v5.5.28
    - don't install illuminate/support v5.4.9|don't install laravel/framework v5.5.28
    - Installation request for laravel/framework (locked at v5.5.28, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.28].
    - Installation request for sule/bank-statements ^1.0 -> satisfiable by sule/bank-statements[v1.0.0, v1.0.1, v1.0.2, v1.0.3].

Installation failed, reverting ./composer.json to its original content.

**Comment by onnayokheng** [comment]
Baru support laravel versi 5.4 sepertinya :)

**Comment by feelinc** [comment]
agak males update composer.json nya 😅 

ayo bantuin update dan test 😁

**Comment by feelinc** [comment]
Uing deui weh :sweat_smile fixed di v1.0.5
