### ISSUE TITLE
Cannot register ServiceProvider

### ISSUE THREAD

**Issue by onnayokheng** [feelinc/laravel-bank-statements#4]
Setelah masukin di config/app.php muncul error.
Versi 5.4, 5.3
 [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method Illuminate\Support\ServiceProvider::register()

**Comment by feelinc** [comment]
Kenapa ya 😅

**Comment by onnayokheng** [comment]
Wkwkwkkw... urang saya ge bingung 🗡

**Comment by feelinc** [comment]
wah kacau kacau kacau 😅

**Comment by feelinc** [comment]
Uing deui weh sweat_smile fixed di v1.0.5
