### ISSUE TITLE
Mandiri Login not working.

### ISSUE THREAD

**Issue by sandeepaquacrm** [feelinc/laravel-bank-statements#5]
When you request to login you get bad request from server. I think its code issue because when i try to run through my own crul script its fine. Please have look into this.

> RuntimeException HTTP/1.1 400 Bad Request Date: Wed, 04 Apr 2018 07:13:53 GMT Accept-Ranges: bytes Content-Length: 2705 Content-Type: text/html Vary: Accept-Encoding

>RuntimeException …/vendor/sule/bank-statements/src/Collector/Web/Mandiri.php149
>Sule\BankStatements\Collector\Web\Mandiri login…/vendor/sule/bank-statements/src/Statement.php293

**Comment by feelinc** [comment]
I could not replicate the issue. Can you share your curl script login HTTP request data, and compare the POST data request with the Mandiri.php class.

Try enable the debug by adding BANK_CLIENT_DEBUG=true to your .env file and share the debug result.

**Comment by sandeepaquacrm** [comment]
![screenshot from 2018-04-04 12-58-49](https://user-images.githubusercontent.com/37613407/38294277-f6d896d4-3807-11e8-9ba6-adca1ec0a525.png)

**Comment by sandeepaquacrm** [comment]
`// set URL and other appropriate options
	set_time_limit(30);
	curl_setopt ($ch, CURLOPT_ENCODING,'gzip');
    curl_setopt ($ch, CURLOPT_URL,"https://ib.bankmandiri.co.id/retail/Login.do?action=form&lang=in_ID");
	if ($proxy > 0){
		curl_setopt($ch, CURLOPT_PROXYPORT, $prox["proxy_port"]);
		curl_setopt($ch, CURLOPT_PROXYTYPE, $prox["proxy_type"]);
		curl_setopt($ch, CURLOPT_PROXY, $prox["proxy_ip"]);
	}
    curl_setopt ($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
    curl_setopt ($ch, CURLOPT_USERAGENT, $user_agent);
	curl_setopt ($ch, CURLOPT_CONNECTTIMEOUT ,90);
    curl_setopt ($ch, CURLOPT_TIMEOUT, 90);
    curl_setopt ($ch, CURLOPT_FOLLOWLOCATION,1);
    curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt ($ch, CURLOPT_COOKIEJAR, getcwd() . $cookie);
    curl_setopt ($ch, CURLOPT_COOKIEFILE, getcwd() . $cookie);
	set_time_limit(30);
    $result0 = curl_exec ($ch);
	$postdata    = "action=" . urlencode("result") . "&userID=" . urlencode("$user") . "&password=" . urlencode("$pass") . "&image.x=" . urlencode("70") . "&image.y=" . urlencode("2");

// set URL and other appropriate options
	set_time_limit(30);
	curl_setopt ($ch, CURLOPT_ENCODING,'gzip');
    curl_setopt ($ch, CURLOPT_URL,"https://ib.bankmandiri.co.id/retail/Login.do");
	if ($proxy > 0){
		curl_setopt($ch, CURLOPT_PROXYPORT, $prox["proxy_port"]);
		curl_setopt($ch, CURLOPT_PROXYTYPE, $prox["proxy_type"]);
		curl_setopt($ch, CURLOPT_PROXY, $prox["proxy_ip"]);
	}
	curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
	curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
    curl_setopt ($ch, CURLOPT_USERAGENT, $user_agent);
	curl_setopt ($ch, CURLOPT_CONNECTTIMEOUT ,90);
    curl_setopt ($ch, CURLOPT_TIMEOUT, 90);
    curl_setopt ($ch, CURLOPT_FOLLOWLOCATION,0);
    curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt ($ch, CURLOPT_REFERER, "https://ib.bankmandiri.co.id/retail/Login.do?action=form&lang=in_ID");
    curl_setopt ($ch, CURLOPT_COOKIEJAR, getcwd() . $cookie);
    curl_setopt ($ch, CURLOPT_COOKIEFILE, getcwd() . $cookie);
	curl_setopt($ch, CURLOPT_POST, 1);
	curl_setopt($ch, CURLOPT_POSTFIELDS, $postdata);
	set_time_limit(30);
    $result = curl_exec ($ch);`

**Comment by feelinc** [comment]
I'm still unable to replicate the issue, it's working correctly here, below should be the result of response body after login

`<html> <head> <title>INTERNET BANKING MANDIRI - Welcome</title> <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"> <meta http-equiv="EXPIRES" content="0"> <meta http-equiv="PRAGMA" content="no-cache"> </head> <frameset border="0" rows="80,*,0"> <frame scrolling="NO" marginwidth=0 marginheight=5 name="top" SRC="common/banner.jsp"> <frameset cols="200,*"> <frame scrolling="AUTO" marginwidth=0 marginheight=1 name="toc" SRC="common/menu.jsp"> <frame noresize="noresize" marginwidth=5 marginheight=5 name=CONTENT src="/retail/Welcome.do?action=result"> </frameset> <frame scrolling="AUTO" marginwidth=5 marginheight=5 name=bottom src="common/bottom.jsp"> </frameset> <noframes> <body bgcolor="#FFFFFF" text="#000000"> </body> </noframes> </html>`

Try check again credentials you set into the collector.

I'm going to close this issue, because the code working correctly.

**Comment by sandeepaquacrm** [comment]
$data = [
          'title'         => 'Mandiri',
          'url'           => 'https://ib.bankmandiri.co.id',
          'collector'     => 'mandiri',
          'name'          => $collectorName,
          'user_id'       => $collectorUser_id,
          'password'      => encrypt($collectorpassword),
          'last_activity' => time(),
          'created_at'    => new DateTime(),
          'updated_at'    => new DateTime()
      ];
      $accountdetails = $accountProvider->create($data);

is this correct?

**Comment by feelinc** [comment]
Try using the mandiri collector directly

`$mandiri = app(\Sule\BankStatements\Collector\Web\Mandiri::class);
$mandiri->setBaseUri('https://ib.bankmandiri.co.id');
$mandiri->setCredential('yourloginuserid', 'yourrawloginpassword');
$mandiri->landing();

try {
    echo 'LOGIN : '.$mandiri->login().'<br/>';
} catch (\Sule\BankStatements\LoginFailureException $e) {
    echo $e->getMessage();
    exit();
}

$startOfMonth = (Carbon::now())->startOfMonth();
$startDate = (Carbon::now())->subDays(30);
$endDate   = Carbon::now();

if ($startOfMonth->month != $startDate->month || $startOfMonth->year != $startDate->year) {
    $startDate = $startOfMonth;
}

// $startDate = new Carbon('first day of last month');
// $endDate = new Carbon('last day of last month');

try {
    $items = $mandiri->collect($startDate, $endDate);

    echo '<pre>';
    print_r($items);
    echo '</pre>';
} catch (\Symfony\Component\Debug\Exception\FatalThrowableError $e) {
    echo $e->getMessage().'<br/>';
    $mandiri->logout();
} catch (\ErrorException $e) {
    echo $e->getMessage().'<br/>';
    $mandiri->logout();
} catch (\RuntimeException $e) {
    echo $e->getMessage().'<br/>';
    $mandiri->logout();
}

echo 'LOGOUT : '.$mandiri->logout().'<br/>';
exit();`

**Comment by sandeepaquacrm** [comment]
When you fetech statements from Mandiri bank its says - 

TRANSACTION CANNOT BE PROCESSED
Sorry, transaction history cannot be processed because system is currently under maintenance. Please do other transactions or try again in a few moments.

But login directly is fine.


![screenshot from 2018-04-04 16-11-50](https://user-images.githubusercontent.com/37613407/38303177-e5cc0c5c-3822-11e8-9b8a-4666e7360eae.png)

**Comment by feelinc** [comment]
I'm still could not replicate your issues there   , working fine here.

Probably they under maintenance or parameters you sent to the internet banking website does not meet their requirement

**Comment by sandeepaquacrm** [comment]
When I use your code it says account ID not found.
